
package wsCalculadora;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.1
 * 2023-12-10T11:46:44.630+01:00
 * Generated source version: 3.6.1
 *
 */
public final class OperacionesCalculadora_OperacionesCalculadoraPort_Client {

    private static final QName SERVICE_NAME = new QName("http://calculadora/", "OperacionesCalculadoraService");

    private OperacionesCalculadora_OperacionesCalculadoraPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OperacionesCalculadoraService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        OperacionesCalculadoraService ss = new OperacionesCalculadoraService(wsdlURL, SERVICE_NAME);
        OperacionesCalculadora port = ss.getOperacionesCalculadoraPort();

        {
        System.out.println("Invoking implementacionRestar...");
        double _implementacionRestar_arg0 = 0.16998017146605482;
        double _implementacionRestar_arg1 = 0.12225052480676124;
        double _implementacionRestar__return = port.implementacionRestar(_implementacionRestar_arg0, _implementacionRestar_arg1);
        System.out.println("implementacionRestar.result=" + _implementacionRestar__return);


        }
        {
        System.out.println("Invoking implementacionDividir...");
        double _implementacionDividir_arg0 = 0.5871546452764644;
        double _implementacionDividir_arg1 = 0.0033937837100519452;
        try {
            double _implementacionDividir__return = port.implementacionDividir(_implementacionDividir_arg0, _implementacionDividir_arg1);
            System.out.println("implementacionDividir.result=" + _implementacionDividir__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking implementacionMultiplicar...");
        double _implementacionMultiplicar_arg0 = 0.7112689637555802;
        double _implementacionMultiplicar_arg1 = 0.8722255629418175;
        double _implementacionMultiplicar__return = port.implementacionMultiplicar(_implementacionMultiplicar_arg0, _implementacionMultiplicar_arg1);
        System.out.println("implementacionMultiplicar.result=" + _implementacionMultiplicar__return);


        }
        {
        System.out.println("Invoking operar...");
        int _operar_arg0 = 1214151402;
        double _operar_arg1 = 0.10967878675207854;
        try {
            double _operar__return = port.operar(_operar_arg0, _operar_arg1);
            System.out.println("operar.result=" + _operar__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getOperaciones...");
        int _getOperaciones_arg0 = 351564643;
        java.util.List<java.lang.String> _getOperaciones__return = port.getOperaciones(_getOperaciones_arg0);
        System.out.println("getOperaciones.result=" + _getOperaciones__return);


        }
        {
        System.out.println("Invoking implementacionSumar...");
        double _implementacionSumar_arg0 = 0.2671245874827062;
        double _implementacionSumar_arg1 = 0.33844454937911084;
        double _implementacionSumar__return = port.implementacionSumar(_implementacionSumar_arg0, _implementacionSumar_arg1);
        System.out.println("implementacionSumar.result=" + _implementacionSumar__return);


        }
        {
        System.out.println("Invoking implementacionMA...");
        port.implementacionMA();


        }
        {
        System.out.println("Invoking implementacionMO...");
        double _implementacionMO__return = port.implementacionMO();
        System.out.println("implementacionMO.result=" + _implementacionMO__return);


        }
        {
        System.out.println("Invoking implementacionML...");
        port.implementacionML();


        }
        {
        System.out.println("Invoking implementacionUR...");
        double _implementacionUR__return = port.implementacionUR();
        System.out.println("implementacionUR.result=" + _implementacionUR__return);


        }

        System.exit(0);
    }

}
