
package calculadora.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.1
 * Sun Dec 10 11:35:06 CET 2023
 * Generated source version: 3.6.1
 */

@XmlRootElement(name = "operar", namespace = "http://calculadora/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "operar", namespace = "http://calculadora/", propOrder = {"arg0", "arg1"})

public class Operar {

    @XmlElement(name = "arg0")
    private int arg0;
    @XmlElement(name = "arg1")
    private double arg1;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

    public double getArg1() {
        return this.arg1;
    }

    public void setArg1(double newArg1)  {
        this.arg1 = newArg1;
    }

}

