
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package wsCalculadora;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.1
 * 2023-12-10T11:46:44.740+01:00
 * Generated source version: 3.6.1
 *
 */

@javax.jws.WebService(
                      serviceName = "OperacionesCalculadoraService",
                      portName = "OperacionesCalculadoraPort",
                      targetNamespace = "http://calculadora/",
                      wsdlLocation = "file:/C:/Users/PapaYMama/UPM/SC/p3/p3-servidor/src/main/webapp/wsdl/operacionescalculadora.wsdl",
                      endpointInterface = "wsCalculadora.OperacionesCalculadora")

public class OperacionesCalculadoraPortImpl implements OperacionesCalculadora {

    private static final Logger LOG = Logger.getLogger(OperacionesCalculadoraPortImpl.class.getName());

    /* (non-Javadoc)
     * @see wsCalculadora.OperacionesCalculadora#implementacionRestar(double arg0, double arg1)*
     */
    public double implementacionRestar(double arg0, double arg1) {
        LOG.info("Executing operation implementacionRestar");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            double _return = 0.7185489053034844;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see wsCalculadora.OperacionesCalculadora#implementacionDividir(double arg0, double arg1)*
     */
    public double implementacionDividir(double arg0, double arg1) throws Exception_Exception   {
        LOG.info("Executing operation implementacionDividir");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            double _return = 0.8441530301622722;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see wsCalculadora.OperacionesCalculadora#implementacionMultiplicar(double arg0, double arg1)*
     */
    public double implementacionMultiplicar(double arg0, double arg1) {
        LOG.info("Executing operation implementacionMultiplicar");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            double _return = 0.633953921262822;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see wsCalculadora.OperacionesCalculadora#operar(int arg0, double arg1)*
     */
    public double operar(int arg0, double arg1) throws Exception_Exception   {
        LOG.info("Executing operation operar");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            double _return = 0.6754467446165557;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see wsCalculadora.OperacionesCalculadora#getOperaciones(int arg0)*
     */
    public java.util.List<java.lang.String> getOperaciones(int arg0) {
        LOG.info("Executing operation getOperaciones");
        System.out.println(arg0);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal-1598902360";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see wsCalculadora.OperacionesCalculadora#implementacionSumar(double arg0, double arg1)*
     */
    public double implementacionSumar(double arg0, double arg1) {
        LOG.info("Executing operation implementacionSumar");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            double _return = 0.12624094814963516;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see wsCalculadora.OperacionesCalculadora#implementacionMA()*
     */
    public void implementacionMA() {
        LOG.info("Executing operation implementacionMA");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see wsCalculadora.OperacionesCalculadora#implementacionMO()*
     */
    public double implementacionMO() {
        LOG.info("Executing operation implementacionMO");
        try {
            double _return = 0.05779811982273786;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see wsCalculadora.OperacionesCalculadora#implementacionML()*
     */
    public void implementacionML() {
        LOG.info("Executing operation implementacionML");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see wsCalculadora.OperacionesCalculadora#implementacionUR()*
     */
    public double implementacionUR() {
        LOG.info("Executing operation implementacionUR");
        try {
            double _return = 0.4087624946173264;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
